# .streamlit/secrets.toml
[mongodb]
connection_string = "mongodb+srv://ai-art-studio_db:<db_password>@ai-art-studio-cluster.sfgct9f.mongodb.net/?appName=ai-art-studio-cluster"
database_name = "art_research_db"
[openrouter]
api_key = "sk-or-v1-fd7cc8dcf30bf6ad815b4e9d6ad71e58954e576"